# Generated by Django 4.1.13 on 2025-06-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeManagement', '0002_alter_cart_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('brand', models.CharField(choices=[('nike', 'Nike'), ('adidas', 'Adidas'), ('puma', 'Puma'), ('reebok', 'Reebok'), ('bata', 'Bata'), ('woodland', 'Woodland')], max_length=20)),
                ('category', models.CharField(choices=[('mens', "Men's Shoes"), ('womens', "Women's Shoes"), ('sports', 'Sports Shoes'), ('formal', 'Formal Shoes'), ('casual', 'Casual Shoes'), ('sneakers', 'Sneakers'), ('slippers', 'Slippers')], max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.FloatField(default=0.0)),
                ('stock', models.PositiveIntegerField()),
                ('rating', models.FloatField(default=0.0)),
                ('image', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShoeSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(choices=[(5, 'Size 5'), (6, 'Size 6'), (7, 'Size 7'), (8, 'Size 8'), (9, 'Size 9'), (10, 'Size 10'), (11, 'Size 11'), (12, 'Size 12')])),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('cart', models.CharField(default='[]', max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('orderhistory', models.CharField(default='[]', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='email',
            field=models.EmailField(default='ex@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='cart',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
